<a href="https://colab.research.google.com/github/kirubakaranr14/Phonepe_Project/blob/main/PhonePe_data_extractipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/PhonePe/pulse.git

Cloning into 'pulse'...
remote: Enumerating objects: 17904, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 17904 (delta 19), reused 17 (delta 17), pack-reused 17855 (from 2)
Receiving objects: 100% (17904/17904), 26.13 MiB | 12.82 MiB/s, done.
Resolving deltas: 100% (8723/8723), done.
Updating files: 100% (9029/9029), done.

**Aggregation_Insurance_data:**

In [2]:
import pandas as pd
import json
import os

ins_path = '/content/pulse/data/aggregated/insurance/country/india/state/'
Agg_ins_state_list = os.listdir(ins_path)
Agg_ins_state_list

ins_data = {'State': [], 'Year': [], 'Quater': [], 'Transaction_type': [], 'Transaction_count': [], 'Transaction_amount': []}

for i in Agg_ins_state_list:
  p_i = ins_path + i + '/'
  Agg_ins_year = os.listdir(p_i)         ##'/content/pulse/data/aggregated/insurance/country/india/state/'

  for j in Agg_ins_year:
    p_j = p_i + j + '/'
    Agg_ins_year_list = os.listdir(p_j)  ##'/content/pulse/data/aggregated/insurance/country/india/state/any_state/'

    for k in Agg_ins_year_list:
      p_k = p_j + k                      ##'/content/pulse/data/aggregated/insurance/country/india/state/any_state/1.json'

      Data = open(p_k,'r')
      D = json.load(Data)

      for z in D['data']['transactionData']:
        name = z['name']
        count = z['paymentInstruments'][0]['count']
        amount = z['paymentInstruments'][0]['amount']

        ins_data['Transaction_type'].append(name)
        ins_data['Transaction_count'].append(count)
        ins_data['Transaction_amount'].append(amount)
        ins_data['State'].append(i)
        ins_data['Year'].append(j)
        ins_data['Quater'].append(int(k.strip('.json')))

Agg_ins = pd.DataFrame(ins_data)
Agg_ins

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,himachal-pradesh,2023,2,Insurance,4197,8499425.0
1,himachal-pradesh,2023,3,Insurance,3935,7869767.0
2,himachal-pradesh,2023,4,Insurance,5211,11898824.0
3,himachal-pradesh,2023,1,Insurance,3909,7826133.0
4,himachal-pradesh,2021,2,Insurance,1210,1402338.0
...,...,...,...,...,...,...
677,chhattisgarh,2024,1,Insurance,19579,30083259.0
678,chhattisgarh,2022,2,Insurance,7008,10119964.0
679,chhattisgarh,2022,3,Insurance,8849,12119470.0
680,chhattisgarh,2022,4,Insurance,11994,18137856.0
681,chhattisgarh,2022,1,Insurance,6612,10139190.0

In [3]:
D

{'success': True,
 'code': 'SUCCESS',
 'data': {'from': 1640975400000,
  'to': 1648405800000,
  'transactionData': [{'name': 'Insurance',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 6612,
      'amount': 10139190.0}]}]},
 'responseTimestamp': 1692611200397}

Converting the .json data into csv

In [4]:
Agg_ins.to_csv('Agg_ins.csv') ## I convert this data into csv type

Aggregation_Transaction_data:

In [5]:

trans_path = '/content/pulse/data/aggregated/transaction/country/india/state/'
Agg_trans_state = os.listdir(trans_path)
Agg_trans_state

trans_data = { 'State': [], 'Year': [], 'Quater': [], 'Transaction_type': [], 'Transaction_count': [], 'Transaction_amount': [] }

for i in Agg_trans_state:
    p_i = trans_path + i + "/"      #["/content/pulse/data/aggregated/transaction/country/india/state/any_state"]
    Agg_trans_yr = os.listdir(p_i)

    for j in Agg_trans_yr:
        p_j = p_i + j + "/"   #["/content/pulse/data/aggregated/transaction/country/india/state/any_state/2018/"]
        Agg_yr_state_list = os.listdir(p_j)

        for k in Agg_yr_state_list:
          p_k = p_j + k       #["/content/pulse/data/aggregated/transaction/country/india/state/any_state/2018/1.json"]

          Data = open(p_k,'r')
          D = json.load(Data)

          for z in D['data']['transactionData']:
            name=z['name']
            count=z['paymentInstruments'][0]['count']
            amount=z['paymentInstruments'][0]['amount']

            trans_data['Transaction_type'].append(name)
            trans_data['Transaction_count'].append(count)
            trans_data['Transaction_amount'].append(amount)
            trans_data['State'].append(i)
            trans_data['Year'].append(j)
            trans_data['Quater'].append(int(k.strip('.json')))

Agg_trans = pd.DataFrame(trans_data)
Agg_trans

,State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount
0,himachal-pradesh,2023,2,Merchant payments,19954117,1.164301e+10
1,himachal-pradesh,2023,2,Peer-to-peer payments,10781507,3.300809e+10
2,himachal-pradesh,2023,2,Recharge & bill payments,4247339,2.159053e+09
3,himachal-pradesh,2023,2,Financial Services,27709,3.468993e+07
4,himachal-pradesh,2023,2,Others,50923,3.022130e+07
...,...,...,...,...,...,...
5029,chhattisgarh,2022,1,Merchant payments,48236094,3.382255e+10
5030,chhattisgarh,2022,1,Peer-to-peer payments,37457039,1.183939e+11
5031,chhattisgarh,2022,1,Recharge & bill payments,11466264,5.442873e+09
5032,chhattisgarh,2022,1,Financial Services,52918,5.599170e+07
5033,chhattisgarh,2022,1,Others,200977,1.317731e+08

In [6]:
Agg_trans.to_csv('Agg_trans.csv')

Aggregation_User_data:

In [7]:
user_path = '/content/pulse/data/aggregated/user/country/india/state/'
Agg_user_state = os.listdir(user_path)
Agg_user_state

user_data = { 'State': [], 'Year': [], 'Quater': [], 'Brand': [], 'Count': [], 'Percentage': [] }

for i in Agg_user_state:
  p_i = user_path + i + "/"
  Agg_user_state_list = os.listdir(p_i)

  for j in Agg_user_state_list:
    p_j = p_i + j + "/"
    Agg_user_year_list = os.listdir(p_j)

    for k in Agg_user_year_list:
      p_k = p_j + k

      Data = open(p_k, 'r')
      D = json.load(Data)

      if D['data']['usersByDevice'] is not None: ## Sometimes phonepe dataset may not have data in .json file, python consider that "UserbyDevice = NULL"
                                                 ## make sure to write condition whether .json is Null before entering into loop..!
        for z in D['data']['usersByDevice']:
          brand = z['brand']
          count = z['count']
          percentage = z['percentage']

          user_data['Brand'].append(brand)
          user_data['Count'].append(count)
          user_data['Percentage'].append(percentage)
          user_data['State'].append(i)
          user_data['Year'].append(j)
          user_data['Quater'].append(int(k.strip('.json')))

Agg_user = pd.DataFrame(user_data)
Agg_user

                 State  Year  Quater    Brand   Count  Percentage
0     himachal-pradesh  2021       2   Xiaomi  513196    0.294407
1     himachal-pradesh  2021       2  Samsung  260440    0.149408
2     himachal-pradesh  2021       2     Vivo  254841    0.146196
3     himachal-pradesh  2021       2     Oppo  217962    0.125039
4     himachal-pradesh  2021       2   Realme  128488    0.073710
...                ...   ...     ...      ...     ...         ...
6727      chhattisgarh  2022       1  OnePlus   99485    0.016814
6728      chhattisgarh  2022       1    Apple   96555    0.016318
6729      chhattisgarh  2022       1    Tecno   57754    0.009761
6730      chhattisgarh  2022       1  Infinix   53501    0.009042
6731      chhattisgarh  2022       1   Others  344930    0.058295

[6732 rows x 6 columns]

In [8]:
print(D)

{'success': True, 'code': 'SUCCESS', 'data': {'aggregated': {'registeredUsers': 5916961, 'appOpens': 448503438}, 'usersByDevice': [{'brand': 'Vivo', 'count': 1531319, 'percentage': 0.2588016044046936}, {'brand': 'Xiaomi', 'count': 1301387, 'percentage': 0.21994179106470366}, {'brand': 'Samsung', 'count': 843988, 'percentage': 0.14263876337870066}, {'brand': 'Oppo', 'count': 702141, 'percentage': 0.11866581510339513}, {'brand': 'Realme', 'count': 629948, 'percentage': 0.1064647882587024}, {'brand': 'Micromax', 'count': 255953, 'percentage': 0.043257510063020525}, {'brand': 'OnePlus', 'count': 99485, 'percentage': 0.01681352978327895}, {'brand': 'Apple', 'count': 96555, 'percentage': 0.016318343149464735}, {'brand': 'Tecno', 'count': 57754, 'percentage': 0.009760753873483364}, {'brand': 'Infinix', 'count': 53501, 'percentage': 0.009041972728905936}, {'brand': 'Others', 'count': 344930, 'percentage': 0.058295128191651086}]}, 'responseTimestamp': 1651127683474}

In [9]:
Agg_user.to_csv('Agg_user.csv')

## MAP [INSURANCE, TRANSACTION, USER]

## Map_Insurance :

In [10]:
map_ins_path = '/content/pulse/data/map/insurance/hover/country/india/state/'
map_ins_state = os.listdir(map_ins_path)
map_ins_state

map_ins_data = {'State': [], 'Year': [], 'Quater': [], 'District': [], 'Count': [], 'Amount': []}

for i in map_ins_state:
    p_i = map_ins_path + i + '/'
    Map_ins_yr = os.listdir(p_i)

    for j in Map_ins_yr:
        p_j = p_i + j + '/'
        Map_ins_yr_list = os.listdir(p_j)

        for k in Map_ins_yr_list:
            p_k = p_j + k

            Data = open(p_k, 'r')
            D = json.load(Data)

            for z in D['data']['hoverDataList']:
              district_name = z['name']
              count = z['metric'][0]['count']
              amount = z['metric'][0]['amount']

              map_ins_data['State'].append(i)
              map_ins_data['Year'].append(j)
              map_ins_data['Quater'].append(int(k.strip('.json')))

              map_ins_data['District'].append(district_name)
              map_ins_data['Count'].append(count)
              map_ins_data['Amount'].append(amount)

map_ins = pd.DataFrame(map_ins_data)
map_ins

                  State  Year  Quater             District  Count     Amount
0      himachal-pradesh  2023       2       solan district    878  1427609.0
1      himachal-pradesh  2023       2     sirmaur district    289   518018.0
2      himachal-pradesh  2023       2      shimla district    351   883035.0
3      himachal-pradesh  2023       2    bilaspur district    144   317410.0
4      himachal-pradesh  2023       2    hamirpur district    371   718811.0
...                 ...   ...     ...                  ...    ...        ...
13871      chhattisgarh  2022       1     bijapur district     82    60717.0
13872      chhattisgarh  2022       1    bemetara district     89   147479.0
13873      chhattisgarh  2022       1      bastar district    158   380450.0
13874      chhattisgarh  2022       1   kondagaon district     78   116490.0
13875      chhattisgarh  2022       1  mahasamund district    161   253785.0

[13876 rows x 6 columns]

Here I convert .json file to CSV :

In [11]:
map_ins.to_csv('map_ins.csv')

Map_Transactions :

In [12]:
map_trans = '/content/pulse/data/map/transaction/hover/country/india/state/'
map_trans_state = os.listdir(map_trans)
map_trans_state

map_trans_data = {'state':[], 'year':[], 'quater':[], 'district':[], 'count':[], 'amount':[]}

for i in map_trans_state:
  p_i = map_trans + i + '/'
  map_trans_state_list = os.listdir(p_i)

  for j in map_trans_state_list:
    p_j = p_i + j + '/'
    map_trans_year_list = os.listdir(p_j)

    for k in map_trans_year_list:
      p_k = p_j + k

      Data = open(p_k, 'r')
      D = json.load(Data)

      for z in D['data']['hoverDataList']:
        name = z['name']
        count = z['metric'][0]['count']
        amount = z['metric'][0]['amount']

        map_trans_data['state'].append(i)
        map_trans_data['year'].append(j)
        map_trans_data['quater'].append(int(k.strip('.json')))

        map_trans_data['district'].append(name)
        map_trans_data['count'].append(count)
        map_trans_data['amount'].append(amount)

map_trans_list = pd.DataFrame(map_trans_data)
map_trans_list

,state,year,quater,district,count,amount
0,himachal-pradesh,2023,2,solan district,8225202,7.869249e+09
1,himachal-pradesh,2023,2,sirmaur district,2641707,3.153309e+09
2,himachal-pradesh,2023,2,shimla district,3935607,5.853301e+09
3,himachal-pradesh,2023,2,bilaspur district,1211407,1.839856e+09
4,himachal-pradesh,2023,2,hamirpur district,1880638,2.572731e+09
...,...,...,...,...,...,...
20599,chhattisgarh,2022,1,bijapur district,651494,1.407049e+09
20600,chhattisgarh,2022,1,bemetara district,1259037,2.287659e+09
20601,chhattisgarh,2022,1,bastar district,2203676,4.004268e+09
20602,chhattisgarh,2022,1,kondagaon district,972613,1.804893e+09
20603,chhattisgarh,2022,1,mahasamund district,2788159,5.020018e+09

In [13]:
map_trans_list.to_csv('map_trans_list.csv')

Map_User :

In [14]:

# 1. Path to map user :
map_user_path = '/content/pulse/data/map/user/hover/country/india/state/'
map_user_state = os.listdir(map_user_path)
map_user_state

# 2. Initialize dictionary :
map_user_list = {'state': [], 'year': [], 'quater': [], 'district': [], 'registeredUsers': [], 'appOpens': []}

#3. for loop :
for i in map_user_state:
  p_i = map_user_path + i + '/'
  map_user_state_list = os.listdir(p_i)

  for j in map_user_state_list:
    p_j = p_i + j + '/'
    map_user_year_list = os.listdir(p_j)

    for k in map_user_year_list:
      p_k = p_j + k

      Data = open(p_k, 'r')
      D = json.load(Data)

      if D['data']['hoverData'] is not None:
        for district, values in D['data']['hoverData'].items():
          map_user_list['state'].append(i)
          map_user_list['year'].append(j)
          map_user_list['quater'].append(int(k.strip('.json')))
          map_user_list['district'].append(district) # <--- Now 'district' is defined!
          map_user_list['registeredUsers'].append(values['registeredUsers'])
          map_user_list['appOpens'].append(values['appOpens'])

#4. Create the DataFrame:
map_user = pd.DataFrame(map_user_list)
map_user

,state,year,quater,district,registeredUsers,appOpens
0,himachal-pradesh,2023,2,solan district,523060,10807448
1,himachal-pradesh,2023,2,sirmaur district,195687,16162360
2,himachal-pradesh,2023,2,shimla district,335735,19477246
3,himachal-pradesh,2023,2,bilaspur district,131239,5385585
4,himachal-pradesh,2023,2,hamirpur district,182553,3589504
...,...,...,...,...,...,...
20603,chhattisgarh,2022,1,bijapur district,46540,6589775
20604,chhattisgarh,2022,1,bemetara district,118600,11001712
20605,chhattisgarh,2022,1,bastar district,142818,14540720
20606,chhattisgarh,2022,1,kondagaon district,77846,14700267
20607,chhattisgarh,2022,1,mahasamund district,185227,20154360

In [15]:
map_user.to_csv('map_user.csv')

**Top_Insurance**

In [16]:
top_ins_path = '/content/pulse/data/top/insurance/country/india/state/'
top_ins_state = os.listdir(top_ins_path)

top_ins_data = {'state': [], 'year': [], 'quater': [], 'districts': [], 'count': [], 'amount':[]}

for i in top_ins_state:
  p_i = top_ins_path + i + '/'
  top_ins_state_list = os.listdir(p_i)

  for j in top_ins_state_list:
    p_j = p_i + j + '/'
    top_user_year_list = os.listdir(p_j)

    for k in top_user_year_list:
      p_k = p_j + k

      Data = open(p_k, 'r')
      D = json.load(Data)


      for z in D['data']['districts']:

        enitityName = z['entityName']
        count = z['metric']['count']
        amount = z['metric']['amount']

        top_ins_data['state'].append(i)
        top_ins_data['year'].append(j)
        top_ins_data['quater'].append(int(k.strip('.json')))
        top_ins_data['districts'].append(enitityName)
        top_ins_data['count'].append(count)
        top_ins_data['amount'].append(amount)

top_ins_list = pd.DataFrame(top_ins_data)
top_ins_list

                 state  year  quater       districts  count     amount
0     himachal-pradesh  2023       2          kangra    979  2087628.0
1     himachal-pradesh  2023       2           solan    878  1427609.0
2     himachal-pradesh  2023       2           mandi    373   750098.0
3     himachal-pradesh  2023       2        hamirpur    371   718811.0
4     himachal-pradesh  2023       2          shimla    351   883035.0
...                ...   ...     ...             ...    ...        ...
5603      chhattisgarh  2022       1  janjgir champa    302   488142.0
5604      chhattisgarh  2022       1         surguja    225   347658.0
5605      chhattisgarh  2022       1     rajnandgaon    207   330899.0
5606      chhattisgarh  2022       1          kanker    201   301862.0
5607      chhattisgarh  2022       1    baloda bazar    185   345262.0

[5608 rows x 6 columns]

In [17]:
top_ins_list.to_csv('top_ins_list.csv')

**Top_transaction:**

In [18]:
top_trans_path = '/content/pulse/data/top/transaction/country/india/state/'
top_trans_state = os.listdir(top_trans_path)
top_trans_state

top_trans_user = {'state': [], 'year': [], 'quater': [], 'districts': [], 'count': [], 'amount':[]}

for i in top_trans_state:
  p_i = top_trans_path + i + '/'
  top_trans_state_list = os.listdir(p_i)

  for j in top_trans_state_list:
    p_j = p_i + j + '/'
    top_trans_year_list = os.listdir(p_j)

    for k in top_trans_year_list:
      p_k = p_j + k

      Data = open(p_k, 'r')
      D = json.load(Data)

      for z in D['data']['districts']:

        enitityName = z['entityName']
        count = z['metric']['count']
        amount = z['metric']['amount']

        top_trans_user['state'].append(i)
        top_trans_user['year'].append(j)
        top_trans_user['quater'].append(int(k.strip('.json')))
        top_trans_user['districts'].append(enitityName)
        top_trans_user['count'].append(count)
        top_trans_user['amount'].append(amount)

top_trans_list = pd.DataFrame(top_trans_user)
top_trans_list

                 state  year  quater       districts    count        amount
0     himachal-pradesh  2023       2           solan  8225202  7.869249e+09
1     himachal-pradesh  2023       2          kangra  6314902  8.889538e+09
2     himachal-pradesh  2023       2          shimla  3935607  5.853301e+09
3     himachal-pradesh  2023       2           kullu  3547410  6.190891e+09
4     himachal-pradesh  2023       2           mandi  2832817  4.073789e+09
...                ...   ...     ...             ...      ...           ...
8291      chhattisgarh  2022       1  janjgir champa  5495226  8.737069e+09
8292      chhattisgarh  2022       1     rajnandgaon  3505850  6.015131e+09
8293      chhattisgarh  2022       1         surguja  3182242  5.281342e+09
8294      chhattisgarh  2022       1    baloda bazar  2925957  5.025354e+09
8295      chhattisgarh  2022       1      mahasamund  2788159  5.020018e+09

[8296 rows x 6 columns]

In [19]:
top_trans_list.to_csv('top_trans_list.csv')

## Top User:

In [20]:
top_user_path = '/content/pulse/data/top/user/country/india/state/'
top_user_state = os.listdir(top_user_path)
top_user_state

top_user_data = {'state': [], 'year': [], 'quater': [], 'pincodes': [], 'registeredUsers': []}

for i in top_user_state:
  p_i = top_user_path + i + '/'
  top_user_state_list = os.listdir(p_i)

  for j in top_user_state_list:
    p_j = p_i + j + '/'
    top_user_year_list = os.listdir(p_j)

    for k in top_user_year_list:
      p_k = p_j + k

      Data = open(p_k, 'r')
      D = json.load(Data)

      try:

        for z in D['data']['pincodes']:
          name = z['name']
          registeredUsers = z['registeredUsers']

          top_user_data['state'].append(i)
          top_user_data['year'].append(j)
          top_user_data['quater'].append(int(k.strip('.json')))
          top_user_data['pincodes'].append(name)
          top_user_data['registeredUsers'].append(registeredUsers)

      except KeyError:
                continue

top_user_list = pd.DataFrame(top_user_data)
top_user_list

                 state  year  quater pincodes  registeredUsers
0     himachal-pradesh  2023       2   173205           202511
1     himachal-pradesh  2023       2   174101           106155
2     himachal-pradesh  2023       2   173025            64829
3     himachal-pradesh  2023       2   173212            45684
4     himachal-pradesh  2023       2   175131            41927
...                ...   ...     ...      ...              ...
9995      chhattisgarh  2022       1   496005            98838
9996      chhattisgarh  2022       1   492009            92386
9997      chhattisgarh  2022       1   490023            91792
9998      chhattisgarh  2022       1   495450            80200
9999      chhattisgarh  2022       1   494001            79440

[10000 rows x 5 columns]

In [21]:
top_user_list.to_csv('top_user_list.csv')

## India Map